import streamlit as st
import google.generativeai as genai
import requests

# --- API SETUP ---
try:
    API_KEY = st.secrets["GEMINI_API_KEY"]
    genai.configure(api_key=API_KEY)
    # Model-ai GEMINI-PRO-ku mathiyachu for maximum compatibility
    model = genai.GenerativeModel('gemini-pro') 
except Exception as e:
    st.error(f"Maddy, API Key-la issue: {e}")

# --- APP CONFIG ---
st.set_page_config(page_title="Mad Gen AI", page_icon="🎨", layout="wide")

st.markdown("""
    <style>
    .stApp { background: linear-gradient(to right, #1e1e2f, #232235); color: white; }
    .stButton>button { border-radius: 20px; background: #FF4B4B; font-weight: bold; color: white; }
    </style>
    """, unsafe_allow_html=True)

st.title("🔥 Mad Gen: Pro Edition")

col1, col2 = st.columns([1, 1])

with col1:
    user_input = st.text_area("Enna creative venum?", placeholder="Eg: Pongal Holiday poster...")
    style_type = st.select_slider("Quality Style:", options=["Minimalist", "High-End Professional", "Cinematic 8K", "Hyper-Realistic"])
    
    if st.button("Mad Gen, Magic Pannu! ✨"):
        if user_input:
            with st.spinner("Mad Gen is thinking..."):
                try:
                    # Input-ai AI-ku simple-ah anupuroam
                    prompt = f"Create a short catchy Tamil marketing tagline and 3 hashtags for: {user_input}"
                    response = model.generate_content(prompt)
                    
                    if response.text:
                        st.session_state['ai_text'] = response.text
                        # High quality Image logic
                        st.session_state['img_url'] = f"https://pollinations.ai/p/{user_input.replace(' ', '%20')}?width=1080&height=1080&seed=123&model=flux"
                        st.session_state['generated'] = True
                except Exception as ai_err:
                    st.error(f"Maddy, API Key-ai oru thadava refresh panni secrets-la podunga. Error: {ai_err}")
        else:
            st.warning("Input kudunga Maddy!")

with col2:
    if 'generated' in st.session_state:
        st.subheader("🚀 Mad Gen Result")
        st.success(st.session_state['ai_text'])
        st.image(st.session_state['img_url'], caption="Generated by Mad Gen")
        
        # Download Logic
        try:
            img_data = requests.get(st.session_state['img_url']).content
            st.download_button(label="📥 Download Image", data=img_data, file_name="mad_gen_poster.png", mime="image/png")
        except:
            st.write("Image-ai long press panni save pannunga!")

st.divider()
st.caption("Mad Gen AI | Model Updated to Gemini-Pro ✅")
